FROM alpine

RUN apk update

RUN apk add ncurses-dev gcc libc-dev flex bison linux-headers make git gdb

COPY debugrc /root/.nethackrc

WORKDIR /app

RUN git clone --depth 1 https://github.com/Chris-plus-alphanumericgibberish/dNAO.git --branch devel-3.21.2 dnh

RUN cd dnh && sed -i -e "s/\/\* set nvrange \*\//iflags.debug_fuzzer = 1;/" src/u_init.c

RUN cd dnh && make -j 4 install

WORKDIR /app/dnh/

CMD /bin/sh
